name: Create Release & Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract Version
      run: |
        echo "VERSION_MAJOR=$(cat src/version.h | grep VERSION_MAJOR | awk '{print $3}')" >> $GITHUB_ENV
        echo "VERSION_MINOR=$(cat src/version.h | grep VERSION_MINOR | awk '{print $3}')" >> $GITHUB_ENV
        echo "VERSION_PATCH=$(cat src/version.h | grep VERSION_PATCH | awk '{print $3}')" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "output/*.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{VERSION_MAJOR}}.${{VERSION_MINOR}}.${{VERSION_PATCH}}